//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chun.Demo.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class errorpath
    {
        public int id { get; set; }
        public string error_path { get; set; }
        public Nullable<System.DateTime> error_CreateTime { get; set; }
        public Nullable<int> error_Update { get; set; }
        public Nullable<System.DateTime> error_UpdateTime { get; set; }
        public Nullable<int> error_type { get; set; }
        public Nullable<int> error_Status { get; set; }
    }
}
