//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chun.Demo.Model.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class phrasehtmlEntities : DbContext
    {
        public phrasehtmlEntities()
            : base("name=phrasehtmlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<errorpath> errorpath { get; set; }
        public virtual DbSet<filepath> filepath { get; set; }
        public virtual DbSet<filestatus> filestatus { get; set; }
        public virtual DbSet<category_info> category_info { get; set; }
    }
}
