//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chun.Demo.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class filepath
    {
        public int id { get; set; }
        public string file_Path { get; set; }
        public string file_innerTxt { get; set; }
        public Nullable<int> file_Type_id { get; set; }
        public Nullable<int> file_status_id { get; set; }
        public Nullable<System.DateTime> file_CreateTime { get; set; }
        public Nullable<System.DateTime> file_updateTime { get; set; }
        public string file_parent_path { get; set; }

    }
}
