//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainForm.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 客户端遇到问题需要关闭，请联系技术支持。 的本地化字符串。
        /// </summary>
        internal static string ClientClosed {
            get {
                return ResourceManager.GetString("ClientClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动客户端失败.  的本地化字符串。
        /// </summary>
        internal static string ClientStartupFail {
            get {
                return ResourceManager.GetString("ClientStartupFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成！你可能需要执行多次以删除空文件夹！ 的本地化字符串。
        /// </summary>
        internal static string DeletedDirDone {
            get {
                return ResourceManager.GetString("DeletedDirDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在进行其他操作 的本地化字符串。
        /// </summary>
        internal static string DoOtherWork {
            get {
                return ResourceManager.GetString("DoOtherWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在执行{0},请耐心等待…… 的本地化字符串。
        /// </summary>
        internal static string IsRunning {
            get {
                return ResourceManager.GetString("IsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 输入的是 String 的本地化字符串。
        /// </summary>
        internal static string MainForm_SayHello_输入的是_String {
            get {
                return ResourceManager.GetString("MainForm_SayHello_输入的是_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的是int 的本地化字符串。
        /// </summary>
        internal static string MainForm_SayHello_输入的是int {
            get {
                return ResourceManager.GetString("MainForm_SayHello_输入的是int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的是int[] 的本地化字符串。
        /// </summary>
        internal static string MainForm_SayHello_输入的是int__ {
            get {
                return ResourceManager.GetString("MainForm_SayHello_输入的是int__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的是string[] 的本地化字符串。
        /// </summary>
        internal static string MainForm_SayHello_输入的是string__ {
            get {
                return ResourceManager.GetString("MainForm_SayHello_输入的是string__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出现了失败！ 的本地化字符串。
        /// </summary>
        internal static string MainForm_打开文件ToolStripMenuItem_Click_ {
            get {
                return ResourceManager.GetString("MainForm_打开文件ToolStripMenuItem_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon Spider {
            get {
                object obj = ResourceManager.GetObject("Spider", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
